### DISCUSSION TITLE
How to filter toml from Markdown

### DISCUSSION THREAD

**Discussion by RobinBeismann** [facelessuser/pyspelling#148] [Q&A] [answered]
Hey,

I'm trying to filter a toml header from a markdown file using the context filter, however I can't get it to drop the toml header from the spellcheck.

Here is an example file I'm matching against:
https://raw.githubusercontent.com/system32blog/blog/preview/content/post/PRTGSensorDiscovery.md

This is how my spellcheck configuration looks (github action):
```
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
      - open: '(?s)^\+{3}$'
        close: '^\+{3}$'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:  
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
```

Does anyone have an idea what I'm doing wrong?

Thanks,
Robin

**Comment by facelessuser** [comment, marked as answer]
I do not see anything obviously wrong. I'm assuming this is how you are avoiding the Toml header?

```yaml
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
      - open: '(?s)^\+{3}$'
        close: '^\+{3}$'
```

If so, it seemed to work for me. I tested it by copying this to the top of one of my Markdown files which is under spell testing, nothing in it was picked up. Unless I'm missing some subtle mistake in your config, it should work just fine.

```
+++
title = "PowerShell based PRTG Sensor Discovery"
date = "2021-11-08"
description = "Use PowerShell to discover sensors on systems."
featured = true
tags = [
    "Robin Beismann"
]
categories = [
    "PowerShell",
    "PRTG",
    "Discovery"
]
series = [""]
aliases = [""]
thumbnail = "post/PRTGSensorDiscovery/logo.png"
+++
```
