### DISCUSSION TITLE
Filtering with pyspelling.filters.context

### DISCUSSION THREAD

**Discussion by gllmflndn** [facelessuser/pyspelling#165] [Q&A] [answered]
I am trying to filter out things like this `:fontawesome-solid-graduation-cap:` from Markdown files with `pyspelling.filters.context`:

```
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '^:'
        content: '[a-z0-9\-]*'
        close: ':$'
```

but I still get `fontawesome` flagged as a spelling error. Any solution for this?

**Comment by facelessuser** [comment, marked as answer]
I don't know what other filters you are using, but assuming you aren't using the Markdown filter and enabling the emoji extension to process the emoji, you could do something like this:

```yaml
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: ':'
        content: '[\w-]+'
        close: ':'
```

We don't know if they will be at the start of the chunk being evaluated so we don't want to specify `^`. We also don't know if it will be at the end, so we won't use `$`.

**Reply by gllmflndn** [reply]
Thanks @facelessuser It now works.

I had misunderstood how the regular expression worked in this context. My full pipeline is like this:

```
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '^--8<--'
        close: 'md"'
      - open: ':'
        content: '[\w-]*'
        close: ':'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - blockquote
      - span
      - a
  - pyspelling.filters.url:
```

It's a mixture of copy-pastes and random guesses.
