### DISCUSSION TITLE
Output the list of spelling mistakes to a file

### DISCUSSION THREAD

**Discussion by MrHinsh** [facelessuser/pyspelling#168] [Q&A]
I would like to be able to output the spelling mistakes to a file/variable for use as input to another task in my GitHub Action.

**How do I output the list of spelling mistakes to a file?**

```yaml
# Current Workflow for Action
name: Validate SDK

on:
  push:
    branches:
    - main
    
jobs:
  validate:
    name: Check SDK
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: igsekor/pyspelling-any@v1.0.4
        name: Spellcheck
```

```yaml
# Configuration
matrix:
- name: Markdown
  sources:
  - '**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
```
