### DISCUSSION TITLE
How to spellcheck only specific sections of a YAML document?

### DISCUSSION THREAD

**Discussion by nasbench** [facelessuser/pyspelling#183] [Q&A] [answered]
Hi,

Just have a quick question regarding the usage of context filters. (and if its the correct way of using them)

I have a yaml document in the following form

```yml
title: Title
id: SomeID
description: Some description
references:
    - https://google.com
data:
    element1: process_creation
    element2: windows
detection:
    some_random_1:
        - random1: 1
        - random2: 2
    some_random_2:
        random|contains:
            - 'A'
            - 'B'
    condition: this is a condition
other:
    - some other things
final: something
```

I wan spell check only some sections of the document mainly the description and title and some other fields.

Is using the `pyspelling.filters.context` the correct approach? If so can you explain how would go about achieving this. If not is its possible to do such thing with pyspelling.

Appreciate your response in advance :)

Thanks
