### DISCUSSION TITLE
Use custom dictionary with hunspell

### DISCUSSION THREAD

**Discussion by joapuiib** [facelessuser/pyspelling#195] [Q&A] [answered]
Hello,

I'm trying to configure this plugin to spell check my teaching site and need assistance.

I want to use hunspell, because there are dictionaries that support my language dialect with this tool: [ca_Es_valencia](https://github.com/elastic/hunspell/tree/master/dicts/ca_ES_valencia)

I've looked at the documentations and some examples, but I can't figure out how to use this custom dictionary.

- https://github.com/facelessuser/pyspelling/blob/master/.pyspelling.yml
- https://github.com/facelessuser/pymdown-extensions/blob/main/.pyspelling.yml

This is my current configuration:

```yml
spellchecker: hunspell

matrix:
  - name: mkdocs
    pipeline:
      - pyspelling.filters.html:
          comments: false
          attributes:
          - title
          - alt
          ignores:
          - ':matches(code, pre)'
          - 'a:matches(.magiclink-compare, .magiclink-commit, .magiclink-repository)'
          - '.md-social__link'
          - 'span.keys'
          - '.arithmatex, .md-nav__link, .md-footer-custom-text, .md-source__repository, .headerlink, .md-icon'
      - pyspelling.filters.url:
    sources:
      - site/**/*.html
    hunspell:
      # I've tested with -p option too
      d: docs/src/dictionary/hunspell/ca-ES-valencia.dic
```

Which gives the following error:

```bash
$ pyspelling
ERROR: site/apunts/01_introduccio/01_introduccio/index.html: html>body>div>footer>div>div>div.md-copyright -- Runtime Error: Can't open affix or dictionary files for dictionary named "docs/src/dictionary/hunspell/ca-ES-valencia.dic".
```

Anyone can give me some guidance on how to do this?

I'm trying this in a branch in my project, which can be found at: https://github.com/joapuiib/curs-git/tree/feature/spelling

Thanks in advance.

**Comment by joapuiib** [comment]
I've made some steps:

`hunspell` allows to set a `DICPATH` env variable to tell the location of dictionaries.

Modifying the config to:
```yml
    hunspell:
      d: ca-ES-valencia
```

And running pyspelling like this:

```bash
DICPATH="docs/src/dictionary/hunspell" pyspelling
```

Seems to work.

**Reply by joapuiib** [reply]
Now, I'm trying to set a custom [word list](https://facelessuser.github.io/pyspelling/configuration/#dictionaries-and-personal-wordlists) for works not included in the dictionary.

Are this words case-sensitive or case-insensitive? I guess they are case-sensitive, but just checking.

**Reply by facelessuser** [reply]
I think they are case-sensitive. I usually use Aspell, but I do run Hunspell tests in CI, so I don't recall off hand.

**Reply by joapuiib** [reply]
I've managed to run them locally!

Now I have a problem on GitHub Actions.
https://github.com/joapuiib/curs-git/actions/runs/11533116760/job/32105658295

In the spell cheking section it gives a lot of "Runtime Errors" with no additional information.

```
ERROR: site/apunts/01_introduccio/03_exercici/index.html: html>body>div>main>div>div>article>ol>li -- Runtime Error: 
Context: site/apunts/01_introduccio/03_exercici/index.html: html>body>div>main>div>div>article>ol>li
````

Any guidance on this?

**Reply by facelessuser** [reply]
Please explain how you are setting up your actions. My initial suggestion is to just look at what I'm doing in any my projects actions. Without knowing what you are doing, I can't really make suggestions.

**Reply by facelessuser** [reply]
If I had to guess, there's likely a problem calling Hunspell. We only issue Runtime errors in two places, and the one that makes the most sense is where we call an external command (like Hunspell).

**Reply by facelessuser** [reply, marked as answer]
```yaml
    hunspell:
      r: True
      d: ca_ES_valencia,en_US
```

I'm also not sure how well `-r` plays with Pyspelling.

Have you tried running Pyspelling locally with the steps in your actions (at least the relevant steps)?
