### DISCUSSION TITLE
Filtering out .rst images

### DISCUSSION THREAD

**Discussion by kathryn-ods** [facelessuser/pyspelling#204] [Q&A] [answered]
Hello, 

I'm trying to use a context filter to ignore images in my .rst files when using pyspelling. 

I'd like to ignore blocks like this. 

```
 .. figure:: ../_assets/key-concepts-img0.svg
   :alt: A labelled diagram of a beneficial ownership network. Labelled as 'Subject of beneficial ownership network' is Company E. Labelled as 'Direct relationship' is a solid line connected to Person 2. Labelled as 'Interest' is the text '32% shareholding' which sits on that solid line. Company E is also linked to Company A by a solid line. And Company A is linked to Person 1 by a solid line. Labelled as 'Indirect relationship' is a dotted line connecting Company E to Person 1. The text '45% shareholding' sits on that dotted line. Person 1 is labelled 'Beneficial owner'. Company A is labelled 'Intermediary entity'.
   :figwidth: 85%
   :align: center
```

I'm a bit stuck on writing the correct regex expression for this - I thought I could say something like open: "figure" close: "center" but I think it's more complicated because it goes across several lines perhaps? 

This is my config file currently
```
matrix:
- name: Markdown
  # use aspell british english dictionary 
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    #additional words not included in the general dictionary
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  #ignore urls 
  - pyspelling.filters.url:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # ignore tags
        - open: '.. _'
          close: ':'
        # ignore directives
        - open: '\.\.\s+(figure)::'
          close: 'center'
  sources:
  # runs on the docs files
  - 'docs/**/*.rst'
  default_encoding: utf-8

```

**Comment by facelessuser** [comment]
I'll take a look later today hopefully. Some formats, without something that is context aware, can be difficult to parse. It's one of the reasons I usually parse my documents to something like HTML and then spellcheck them as I think have a format I can easily filter with CSS selectors and such.

With all of that said, I don't really provide anything that handles RST docs currently, so if you must parse raw RST content, then coming up with a regex, context filter can be desirable. I do think it should be possible, we'll just need to likely track indentation and kick out once we see indentation drop below the starting line...or maybe just look for an empty line...

Anyway, when I get a little time, I'll see if I can come up with a solution.

**Reply by kathryn-ods** [reply]
Thank you! Really appreciate you looking at this

**Reply by facelessuser** [reply, marked as answer]
@kathryn-ods Here is an example:

Consider the following file, which has two nonsense words with an image between:

```rst
kkjsk

.. figure:: ../_assets/key-concepts-img0.svg
  :alt: A labelled diagram of a beneficial ownership network. Labelled as 'Subject of beneficial ownership network' is Company E. Labelled as 'Direct relationship' is a solid line connected to Person 2. Labelled as 'Interest' is the text '32% shareholding' which sits on that solid line. Company E is also linked to Company A by a solid line. And Company A is linked to Person 1 by a solid line. Labelled as 'Indirect relationship' is a dotted line connecting Company E to Person 1. The text '45% shareholding' sits on that dotted line. Person 1 is labelled 'Beneficial owner'. Company A is labelled 'Intermediary entity'.
  :figwidth: 85%
  :align: center

dlkjsk
```

Consider the context filter below.

```yaml
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '(?s)^(?P<open> *)\.\. figure::'
        close: '^(?!(?P=open) )'
```

1. We set the DOTALL flag via `(?s)` to ensure things like `.*?` will capture newlines, which is the default pattern for `content`, the stuff in between `open` and `close`. We set this specifically to affect `content` so that `.*?` will capture newlines for an entire block, and not stop at a single line.
2. We use `^` to start capturing at the start of a line and use a capturing group named `open` to capture the leading white space of the first line of the figure, followed by the pattern to capture `.. figure::`.
3. The closing pattern looks for the start of a line that has indentation less than or equal to the level of what we captured in the opening pattern via `(?P<open> *)`. We do this by checking for the start of the line with a negative lookahead that references what we captured in `(?P<open> *)` and adds one additional space. So the first line that has the same indentation as the opening line, or less, triggers the cancellation of the ignore.

Results show that we capture the first nonsense word, skip the entire image, and then capture the last nonsense word.

```console
➜  pyspelling git:(master) ✗ python3 -m pyspelling -n rst
Misspelled words:
<context> test.rst
--------------------------------------------------------------------------------
dlkjsk
kkjsk
--------------------------------------------------------------------------------

!!!Spelling check failed!!!
```
Some additional notes. This won't capture the disparity of tabs vs spaces, so be consistent in your whitespace usage and make your patterns reflect what you actually use.

Hopefully, this helps to make more clearly how the context filter works and how you can use it to your advantage.
