### ISSUE TITLE
Ignore dictionary case from .yml file

### ISSUE THREAD

**Issue by decanus** [facelessuser/pyspelling#108]
Is there any way to ignore a dictionaries case using the yml file?

**Comment by facelessuser** [comment]
Pretty sure you can use the spell checker options to control such things: https://facelessuser.github.io/pyspelling/configuration/#spell-checker-options.

I'm assuming you are using Aspell? If so, I think they're is an `ignore-case` option. You can give that a try.

**Comment by decanus** [comment]
Hmm, doesn't seem to work, I tried it here: https://github.com/status-im/specs/pull/119

**Comment by facelessuser** [comment]
This is what I did:

1. I placed this in my document: `WHSK`. Then ran pyspelling and the test failed:

    ```
    $ pyspelling
    Misspelled words:
    <url-free> README.md: html>body>p
    --------------------------------------------------------------------------------
    WHSK
    --------------------------------------------------------------------------------

    !!!Spelling check failed!!!
    ```

2. Placed `whsk` in my wordlist.

3. Updated my options:

    ```yaml
    matrix:
    - name: markdown
      sources:
      - '*.md'
      aspell:
        lang: en
        ignore-case: true
      dictionary:
        wordlists:
        - .dictionary
        output: build/dictionary/markdown.dic
      pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences:
            - pymdownx.highlight:
      - pyspelling.filters.html:
          comments: false
          attributes:
          - title
          - alt
          ignores:
          - 'code, pre'
      - pyspelling.filters.url:
    ```

4. Re-ran pyspelling:

    ```
    $ pyspelling
    Spelling check passed :)
    ```
