### ISSUE TITLE
Issue with Source Glob Matching for ignore

### ISSUE THREAD

**Issue by mgan59** [facelessuser/pyspelling#109]
## Context

First time setting up pyspell.  Running into an issue.  Want to run pyspell on all my markdown files, EXCEPT what is inside of `node_modules/`.

## Configuration

This is what I have in my `yaml` config

```yaml
matrix:
- name: Markdown
  aspell:
    lang: en
  sources:
  - '**/*.md!node_modules/**/*.md'
  default_encoding: utf-8
```

I've tried a few other variations for sources such as `'**/*.md!node_modules/*'`.  When I run the checker it is still sourcing from the `node_modules/`.
