### ISSUE TITLE
Spellchecking Literate Coding Formats: Jupyter notebooks (ipynb), Rmd etc

### ISSUE THREAD

**Issue by psychemedia** [facelessuser/pyspelling#110]
I've been looking for tools to support command-line spell checking of document formats used in literate computing that support the inclusion of markdown and code blocks, as well as embedded "output" artefacts. For example, Jupyter notebooks (`.ipynb` files), RMarkdown (`.Rmd`) files.

In the case of Jupyter notebooks, the raw document format ([docs](https://nbformat.readthedocs.io/en/latest/)) is a JSON file that identifies different cell types, cell outputs etc.

The [`jupytext`](https://github.com/mwouts/jupytext) package created by @mwouts provides a wide range of tools for converting literate document formats into the `.ipynb` format

For spellchecking such documents, the `.ipynb` cell structure makes it easy to separate markdown, code and and code output areas (though markdown can include backtick blocked code fragments) which makes it easy to handle them differently. The document structure also supports cell tags.

This got me wondering about whether `pyspelling` could be used to handle `ipynb` documents, or documents that can be converted to them (`.Rmd`, Jupytext markdown, various structured Python formats) and then spellchecked appropriately in the different document structure areas:

- markdown ("full" spell check, though with additional handlers for embedded HTML, code blocks);
- code cells (spell check comments and block comments);
- code output cells — ignore?
- cell tags: build up a directory count of these, and then string-distance check on infrequent tags to spot possible typos;

**Comment by facelessuser** [comment]
My current take on this is yes it is possible. I'm not sure exactly what approach should be taken as I'm unfamiliar with this format and such.

Pyspelling provides a number of filters etc. The idea was to provide a number that were analogous to what was available in aspell/hunspell and I of course added some that I specifically have a use for as well. But, the framework is done in such a way that anyone can write their own filters. The key here is to reduce the maintenance cost on me, and have someone intimately familiar with the format that is being filtered maintain it.

I don't do anything with Jupyter notebooks at this time, so I don't really feel I'm the right person to spear head, or support such a filter. But it is possible that maybe you could write your own filter package for pyspelling 🙂 .

The questions I would ask is how much needs to be done by new filters. For instance, this project's documentation is spellchecked by pyspelling itself. It's a MkDocs project, but I don't have a MkDocs filter, I simply run MkDocs to build the documentation as HTML (outside of pyspelling), and run the HTML files through the HTML filter.

It sounds like you have multiple types of data that need to be handled differently. In general, I would probably create a filter that one way or another extracts the content and gives each type of text different categories. Then you can divert which ones go to which filter with: https://facelessuser.github.io/pyspelling/flow_control/wildcard/.

The content that you send may need additional filters to either strip them down to the plain text that you wish to spell check, or manipulate the format to something that can be handled by existing filters.

There are probably numerous creative ways to parse content. I imagine, for instance, that you could run an unfamiliar coding language through something like Pygments, which would return syntax highlighted HTML, but you could use the HTML classes it returns to target text scoped as comments. Just some ideas.

Anyways, I get the impression you are looking for pyspelling to provide a plugin to this, but I'm more of the mind that users should extend pyspelling to fit their specific needs. With that said, if you were to create a plugin and find there are ways that I can improve pyspelling to allow this to be easier, I'm open to suggestions.

**Comment by psychemedia** [comment]
Thanks for that feedback. I'll see how far I can get using `pyspelling` as currently formulated (the markdown filter may be good enough). If it then seems that splitting the `.ipynb` document into subdocuments still makes sense in terms of improving performance or user workflow, I'll see if I can extend `pyspelling` as required.

**Comment by facelessuser** [comment]
Sure, don't be afraid to ask questions though. While I don't necessarily want to be the maintainer of every use case for everyone, I'm more than willing to answer questions and offer guidance as needed. I'm also willing to improve the core code in it helps.

**Comment by psychemedia** [comment]
I think I have a better idea of how this might work now. The `pyspelling` seems to use a series of document conversion filters that eg convert from markdown to HTML, and then allow the omission of particular HTML tags.

The [`jupytext`](https://jupytext.readthedocs.io/en/latest/using-cli.html) package contains a wide range of literate programming document format conversion tools (like pandoc for literate coding files): various flavours of commented pyhton to markdown, ipynb to py, Rmd to ipynb so on.

A `jupytext` filter that accepted `from` and `to` fields could parse various coding file formats into py or md and allow them to feed into pre-existing `pyspelling` pipeline filters and extensions.

In the short term, converting `ipynb` to python, or markdown, allows them to be used with current `pyspelling` filters.

Eg the following hides the leading `---` wrapped YAML header at the start of a *jupytext-md* file and spell checks on the markdown components from the original notebook:

```
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # Ignore the --- wrapped YAML header in jupytext-md file
        - open: '(?s)^(?P<open> *-{3,})$'
          close: '^(?P=open)$'
  - pyspelling.filters.url:
  - pyspelling.filters.markdown:
      markdown_extensions:
        - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      ignores:
        - code
        - pre
        - tt
   ```

I note it would probably also make sense to spell check within comments in the `<code>` and `<pre>` HTML tags (is there a straightforward way of adding such a step to the above fragment?)

**Comment by facelessuser** [comment]
Pygments does have certain classes for comments. It's possible you could not just blindly ignore all pre/code blocks. The HTML filter has some pretty powerful CSS selector support. The filter uses BeautifulSoup, and I wrote the CSS selector library (soupsieve) that it uses.

**Comment by facelessuser** [comment]
Hmm, it might be tricky as the `ignore` option won't crawl children.

**Comment by facelessuser** [comment]
Okay, since SuperFences is using Pygments, and Pygments puts comments (at least the ones I've tested) under the class `c1`, you could do this:

```yml
      captures:
      - '*|*:not(script,style,code)'
      ignores:
      - 'code > *:not(.c1)'
```

`captures` captures the specified elements, but children are still crawled. So we don't capture anything under code, but we still crawl the children under it. Then we ignore all the spans that Pygments creates except the ones with the `c1` class. That should get you comments. Or at least the ones styled under `c1`.

**Comment by psychemedia** [comment]
Cribbing from the markdown filter, I came up with this first quick attempt at an ipynb filter. The `.ipynb` format is a structured JSON format that includes notions of "code" and "markdown" cells. The following attempt lets you extract content from code or markdown cells:

```python
"""Jupyter ipynb document format filter."""
from .. import filters
import codecs
import markdown
import nbformat

class IpynbFilter(filters.Filter):
    """Spellchecking Jupyter notebook ipynb cells."""

    def __init__(self, options, default_encoding='utf-8'):
        """Initialization."""

        super().__init__(options, default_encoding)

    def get_default_config(self):
        """Get default configuration."""

        return {
            'cell_type': 'markdown', # Cell type to filter
            'language': '', # This is the code language for the notebook
            # Optionally specify whether code cell outputs should be spell checked
            'output': False, # TO DO
            # Allow tagged cells to be excluded
            'tags-exclude': ['code-fails']
        }

    def setup(self):
        """Setup."""

        self.cell_type = self.config['cell_type'] if self.config['cell_type'] in ['markdown', 'code'] else 'markdown'
        self.language = self.config['language'].upper()
        self.tags_exclude = set(self.config['tags-exclude'])

    def filter(self, source_file, encoding):  # noqa A001
        """Parse ipynb file."""

        nb = nbformat.read(source_file, as_version=4)
        self.lang = nb.metadata['language_info']['name'].upper() if 'language_info' in nb.metadata else None
        # Allow possibility to ignore code cells if language is set and
        # does not match parameter specified language? E.g. in extreme case:
        #if self.cell_type=='code' and self.config['language'] and self.config['language']!=self.lang:
        #    nb=nbformat.v4.new_notebook()
        # Or maybe better to just rewrite code cells as empty and retain other cells?

        encoding = 'utf-8'

        return [filters.SourceText(self._filter(nb), source_file, encoding, 'ipynb')]

    def _filter(self, nb):
        """Filter ipynb."""

        text_list = []
        for cell in nb.cells:
            if cell['cell_type']==self.cell_type:
                if cell['cell_type']=='code' and 'tags' in cell['metadata'] and \
                    set(cell['metadata']['tags']).intersection(self.tags_exclude):
                    continue
                text_list.append(cell['source'])
        
        return '\n'.join(text_list)

    def sfilter(self, source):
        """Filter."""

        return [filters.SourceText(self._filter(source.text), source.context, source.encoding, 'ipynb')]


def get_plugin():
    """Return the filter."""

    return IpynbFilter

```

The different content can then be passed into different pipelines, eg again at a first attempt:

```
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.ipynb:
      cell_type: markdown
  - pyspelling.filters.url:
  - pyspelling.filters.markdown:
      markdown_extensions:
        - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      ignores:
        - code
        - pre
        - tt
  sources:
    - 'content/*/*.ipynb'
  default_encoding: utf-8
- name: Python
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.ipynb:
      cell_type: code
  - pyspelling.filters.url:
  - pyspelling.filters.python:
  sources:
    - 'content/*/*.ipynb'
  default_encoding: utf-8
```
