### ISSUE TITLE
Ignoring HTML tags does not work

### ISSUE THREAD

**Issue by MichaIng** [facelessuser/pyspelling#118]
We try to exclude `<pre>` and `<code>` content from HTML files for spell checking and tried it first with:
```
    ignores:
    - code
    - pre
```
then with (with and without quotes):
```
- ':matches(code, pre)'
```
last with:
```
- ':is(code, pre)'
```
but none worked, we still see:
```
Misspelled words:
<url-free> build/docs/user-guide_installation/index.html: html>body>div>main>div>div>article>div>div>details>ol>li
--------------------------------------------------------------------------------
wifi
--------------------------------------------------------------------------------
```
Where `wifi` is coming from such parts of the HTML file:
```
<ol>
  <li>Open the file named <code>dietpi-wifi.txt</code></li>
```
There are many other examples. I wonder why the code tag is not even recognised/listed the the path above, if it was completely overseen.

I first though that there might be a maximum tag depth but the same issue as well is present for one occurrence in:
```
html>body>div>main>div>div>article>div>div>p
```

The website is life here: https://dietpi.com/docs/user-guide_installation/
Our repository where PySpelling runs as GitHub action: https://github.com/MichaIng/DietPi-Docs
It runs via https://github.com/rojopolis/spellcheck-github-actions but that should not be relevant since PySpelling itself parses the [config file](https://github.com/MichaIng/DietPi-Docs/blob/master/.spellcheck.yml), successfully for everything else but the tag exclusion.

**Comment by facelessuser** [comment]
@MichaIng, try indenting your options (dictionary keys) a little more.

```yml
matrix:
- name: HTML
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:
  sources:
  - 'build/docs/**/*.html'
  default_encoding: utf-8
```

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by MichaIng** [comment]
Indeed that was the issue, many thanks for pointing it out. Also attributes were not checked for the same reason, which is now shown by a few additional errors 😄.

Any chance to have a syntax error detected in such case? Although, it is no wrong syntax when comparing to other parts:
```
- name: HTML
  aspell:
    lang: en
  dictionary:
```
So basically the non-indented attributes/ignores is correct YAML syntax but assigns values at a wrong place?
