### ISSUE TITLE
Ignoring words containing numbers, hyphens, etc.  

### ISSUE THREAD

**Issue by miff2000** [facelessuser/pyspelling#130]
I have markdown files with all sorts of acronyms and technical words in them. I've added those special words to the dictionary, and that's worked for most, but with terms like `L2TP`, `IPv6`, etc. they seem to have the numbers removed from them before they are spell checked.

Is there any way I can control this? Ideally I would like to ignore any words in their entirety if they are in the custom dictionary

Below shows my current config. You'll see I've that I've added pattern exclusions for `1st`, `2nd`, etc. and `pre-`, `post-`, etc. to tackle those.

```yaml
matrix:
- name: Markdown
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_GB
  dictionary:
    encoding: utf-8
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.url:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      - open: '(?s)^(?P<open> *`{3,})\S+$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>(`|``))+'
        close: '(?P=open)'
      # Ignore everything after :keywords:
      - open: '(:keywords:)+'
        close: '$'
      # Ignore pre-, post- prefixes
      - open: '\W(Pre|pre|Post|post|Un|un)'
        close: '-'
      # Ignore 1st, 2nd, 3rd, etc.
      - open: '\W[0-9]+(?:st|[nr]d|th)'
        close: '\W'
      # Ignore bare URLs, surrounded in <>
      - open: '\W<\w+:\/\/'
        close: '>\W'
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
      - a href
  sources:
  # - 'source/**/*.md'
```
