### ISSUE TITLE
context filter for backtick fences does not work

### ISSUE THREAD

**Issue by KIC** [facelessuser/pyspelling#135]
I have a readme with the following code snipped:
````
```python
from pandas_ml_common import ReScaler

x = np.arange(0, 1, .1)
rescaler = ReScaler((0, 1), (5, -5))

rescaler(x)
array([ 5.,  4.,  3.,  2.,  1.,  0., -1., -2., -3., -4.])
lalalo
```
````

But I can not get pyspelling to ignore the code fragments.
```
Misspelled words:
<url-free> pandas-ml-common/Readme.md: html>body>p
--------------------------------------------------------------------------------
lalalo
rescaler
--------------------------------------------------------------------------------
```

This is my config:
```
spellchecker: aspell

matrix:
- name: markdown
  sources:
  - ./**/*eadme.md
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .en-custom.txt
    output: /tmp/build/dictionary/mkdocs.dic
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
        - title
        - alt
      ignores:
        - code
        - pre
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`]'
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})(.*)$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
  - pyspelling.filters.url:
```

**Comment by facelessuser** [comment]
@KIC, Python Markdown, which is used in the default Markdown filter, does not parse fenced (block backtick) code by default. I would consider installing SuperFences and then enabling it:

```yaml
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
```

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by KIC** [comment]
Yep that one works. thx!

**Comment by lachieh** [comment]
If anyone stumbles across this because they're trying to do this or something similar without the markdown extension, the reason this doesn't work is because by default, the "content" is only allowed to span one line. By adding a `content: "[\\s\\S]*?"` key to the delimiter, it will capture all lines between the open and close expressions.

```yaml
  - pyspelling.filters.context:
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})(.*)$'
        content: "[\\s\\S]*?"
        close: '^(?P=open)$'
```

**Comment by facelessuser** [comment]
`content` is not needed in this case `(?s)` enables capture of newlines with `.` which is used to capture the content by default. You can check this project's configuration to see that we successfully capture multiline content without having to specify `content`: https://github.com/facelessuser/pyspelling/blob/master/.pyspelling.yml#L130.

I suspect your issue is likely due to you capturing multiline content in `open` via `(.*)`. You'd probably do better to use `(.*?)`.

**Comment by lachieh** [comment]
Fair enough, the code in the comment is not my exact use case. I wanted a way to blanket ignore between two specific lines, in this case, inside an mdx file:

```yaml
          # {/* spell-check-disable */} and {/* spell-check-enable */}
          - open: "^\\{\\/\\* spell-check-disable \\*\\/\\}$"
            content: "[\\s\\S]*?"
            close: "^\\{\\/\\* spell-check-enable \\*\\/\\}$"
```

This works fine as defined above, however not without the `content` specifier.
