### ISSUE TITLE
Not ignoring code/pre blocks

### ISSUE THREAD

**Issue by itsjoekent** [facelessuser/pyspelling#156]
Having trouble getting this action to ignore code blocks in my markdown.

Here is my configuration,

```yml
matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .github/wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
```

Here is some sample markdown it's reporting spell check errors for,

```md
## Research Process

To determine if unnecessary DOM mutations were happening, we attached a Mutation Observer to the application with the following code,

``js
function noisyCallback(mutationList) {
  mutationList.forEach((mutation) => {
      console.log("mutation observed", mutation)
  });
}

const el = document.querySelector('#app')

const observer = new MutationObserver(noisyCallback)

observer.observe(el, {characterData: true, characterDataOldValue: true, subtree: true, childList: true, attributes: true, attributeOldValue: true})
``
``` 

**In order to not break the formatting of this Github Issue, I removed a backtick from the start & end of the JS codeblock**. The actual markdown file in question has 3 backticks.

This is the error I am getting,

```
Using pyspelling on configuration outlined in >.github/spellcheck-config.yml<
Checking files matching specified outlined in >.github/spellcheck-config.yml<
----------------------------------------------------------------
Misspelled words:
<htmlcontent> rd/localize-react.md: html>body>p
--------------------------------------------------------------------------------
forEach
mutationList
noisyCallback
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> rd/localize-react.md: html>body>p
--------------------------------------------------------------------------------
const
el
querySelector
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> rd/localize-react.md: html>body>p
--------------------------------------------------------------------------------
MutationObserver
const
noisyCallback
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> rd/localize-react.md: html>body>p
--------------------------------------------------------------------------------
attributeOldValue
characterData
characterDataOldValue
childList
el
subtree
--------------------------------------------------------------------------------
```

As you can see, all of the code is being treated as a paragraph element, not a code or pre element. In the Github render, it is a pre element and renders as a code block:

<img width="1070" alt="Screen Shot 2022-10-13 at 11 44 33 AM" src="https://user-images.githubusercontent.com/897368/195643377-0ad747d0-f3df-4143-ba2b-79f1f6d89a6a.png">

Can someone help me understand why the spell check isn't working?
