### ISSUE TITLE
No module named 'pyspelling.parsers

### ISSUE THREAD

**Issue by gllmflndn** [facelessuser/pyspelling#164]
Thank you @facelessuser for `pyspelling`.

According to the documentation at https://facelessuser.github.io/pyspelling/filters/markdown/, one can define a markdown pipeline with:
```
  pipeline:
  - pyspelling.parsers.markdown_parser:
```
I'm using pyspelling 2.8.2 and I get the error:
```
ModuleNotFoundError: No module named 'pyspelling.parsers'
```

**Comment by facelessuser** [comment]
@gllmflndn Sorry, that was a typo. Should be:

```
matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.toc:
          slugify: !!python/name:pymdownx.slugs.uslugify
          permalink: "\ue157"
      - markdown.extensions.admonition
      - markdown.extensions.smarty
  source:
  - **/*.md
  ```

Just pushed the documentation update.
