### ISSUE TITLE
Could I please have some help with pyspelling in a CI pipeline?

### ISSUE THREAD

**Issue by Alex-Bujorianu** [facelessuser/pyspelling#172]
Hi there,

I am using pyspelling in Github Actions with the following .spellcheck.yaml file:

```
---
spellchecker: aspell
matrix:
  - name: markdown
    aspell:
      lang: en
    sources:
      - "Chapters/*.md"
    pipeline:
      - pyspelling.filters.markdown
    dictionary:
      wordlists:
        - wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    default_encoding: utf-8
    expect_match: true
```

In the CI pipeline I see that it is running this command: `Command: ['aspell', 'list', '--encoding', 'utf-8', '--add-extra-dicts', '/github/workspace/wordlist.dic', '--lang', 'en', '--mode', 'none']`. The custom dictionary seems to have some effect, but it is still showing some of the words as mis-spelt, especially those with apostrophes. The dictionary looks something like this (truncated for brevity):

```
Battleborn
Carthago
Dacian
Dwarvish
Fangtooth
```

What happens if a word is duplicated inside of the dictionary? I think it might be related to that.

Also is there any way to get it to not print the contents of each file that it is checking?

**Comment by facelessuser** [comment]
I would need a minimal reproducible example so that I could troubleshoot the issue. If you can provide that, I might be able to help. I just don't have enough context about your environment to guess what your issue is.

> What happens if a word is duplicated inside of the dictionary? I think it might be related to that.

Nothing, it should work fine.

> What happens if a word is duplicated inside of the dictionary? I think it might be related to that.

There are a couple levels of verbose. You can add increasing `-v`. One `v` is verbose, two `v`s is more verbose, etc.

**Comment by Alex-Bujorianu** [comment]
> I would need a minimal reproducible example so that I could troubleshoot the issue. If you can provide that, I might be able to help. I just don't have enough context about your environment to guess what your issue is.
> 
> > What happens if a word is duplicated inside of the dictionary? I think it might be related to that.
> 
> Nothing, it should work fine.

Yes, it seems you're right, the problem is with the apostrophes. In the minimal example, attached, the word Rahash does not appear in the list of misspelled words, although **Rahash’s** (with an apostrophe) does, even though it's in the dictionary. 

> There are a couple levels of verbose. You can add increasing `-v`. One `v` is verbose, two `v`s is more verbose, etc.

How do I do this in the YAML file (not command line)? It's printing the HTML string of each chapter which is annoying. Example:

![image](https://github.com/facelessuser/pyspelling/assets/75983910/cf957416-8097-4442-9e6b-dc85ed8418e9)

**Comment by facelessuser** [comment]
Aspell doesn't actually have intelligent handling for possessive words. You basically have two options when dealing with possessive words.

1. Add the possessive form to the dictionary.
2. Create a filter that will ignore the possessive part of the word. By ignoring `'s`, the word will be treated as a non-possessive word.

    ```yaml
      - pyspelling.filters.context:
          context_visible_first: true
          delimiters:
          # Ignore possessive endings
          - open: '(?<=\w)''s(?!\w)'
            close: '\b'
    ```
