### ISSUE TITLE
Demonstrate how to use in GitHub CI and/or create a repo with a GitHub action

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pyspelling#93]
Actions are kind of cool, not fully usable yet for everything, but can be used to automate some things.

Pyspelling is a perfect candidate for this. It is actually really easy to do as we just need to setup a simple docker file and entry point, install the requirements and retrieve the `.pyspelling` config (optionally make the name configurable), and run it.

If we create an action, we should provide a link and maybe an example.

At the very least, we can show how to do it by just calling tox (which honestly is probably faster), but it takes a little more setup.

**Comment by facelessuser** [comment]
This is really all anyone needs to get started and integrate pyspelling directly into GitHub CI. This is of course assuming the user only needs Python to handle documentation. If they are using some other toolset to build their documentation first before spell checking, then they have to adapt. If using apt installable modules, they can install them in the `Install Aspell` step.

Below we show places you get add additional spelling plugins, markdown plugins, document building tools, etc. You could easily use requirement file to lock versions, etc.

We also have a step for building documentation if needed.

```yaml
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox
        python -m pip install pyspelling
        # Install any additional libraries required: additional plugins, documentation building libraries, etc.
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Build documents
      run: |
        # Perform any documentation building that might be required
    - name: Spell check
       run: |
         python -m pyspelling
```
